### ISSUE TITLE
requirement.txt version error

### ISSUE THREAD

**Issue by TOBEACODER7** [MetisPrometheus/MSc-thesis-xmkckks#1]
Thanks for your exciting work!
In your requirement.txt
```
grpcio-tools==1.54.0
...
protobuf==3.20.3
```
When using the ```pip install -r requirement. txt```, there is an error about this version conflict.
```
ERROR: Cannot install -r requirements.txt (line 23) and protobuf==3.20.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested protobuf==3.20.3
    grpcio-tools 1.54.0 depends on protobuf<5.0dev and >=4.21.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
Is there any way to solve this error?

**Comment by MetisPrometheus** [comment]
Hi,

Thank you and sorry for answering late. I do not frequently check this
email.

In case you didn't resolve the issue you could just modify the
requirements.txt file to replace the line "protobuf==3.20.32" with just
"protobuf"

That way, pip will automatically find a compatible protobuf version to
satisfy the requirements of grpcio-tools, and it should not break the rest
of the code.

Best Regards,
Ivar W.



ons. 11. okt. 2023 kl. 15:37 skrev Lawrence_Yang ***@***.***>:

**Comment by TOBEACODER7** [comment]
Thanks again for your work and open-source code.
